name: aondeir_motorista
description: A new Flutter project.

publish_to: 'none' 

version: 1.3.58+105

package: com.aondeir.motoristaapp

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  easy_stepper: ^0.8.5+1
  syncfusion_flutter_datepicker: ^21.1.39
  quantity_input: ^1.0.2
  indexed: ^0.0.8
  uuid: ^4.5.1
  sliding_up_panel: ^2.0.0+1
  flutter_svg: ^2.0.5
  geolocator: ^13.0.2
  flutter_rating_bar: ^4.0.1
  persistent_bottom_nav_bar: ^6.2.1
  flutter_masked_text2: ^0.9.1
  flutter_credit_card: ^4.1.0
  charts_flutter: ^0.12.0
  slidable_button: ^3.0.0+1
  url_launcher: ^6.1.11
  map_launcher: ^3.5.0
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.4
  mask_text_input_formatter: ^2.5.0
  socket_io_client: ^3.0.2
  qr_flutter: ^4.0.0
  intl: ^0.17.0
  flutter_spinkit: ^5.1.0
  camera: ^0.11.1
  path_provider: ^2.0.5
  dio: ^5.4.0
  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.3
  flutter_local_notifications: ^18.0.1
  flutter_overlay_window: ^0.5.0
  permission_handler: ^11.0.1
  audioplayers: ^6.3.0
  connectivity_plus: ^6.1.3
  geocoding: ^3.0.0
  flutter_overlay_apps: ^1.2.0
  image_picker: ^1.0.7
  flutter_pdfview: ^1.4.3
  flutter_foreground_task: ^8.17.0
  just_audio: ^0.9.37
  file_picker: ^9.0.0
  carousel_slider: ^5.0.0
  app_tracking_transparency: ^2.0.0
  android_intent_plus: ^4.0.0
  flutter_native_splash: ^2.4.3
  pin_code_fields: ^8.0.1
  flutter_launcher_icons: ^0.14.3
  volume_controller: ^3.4.0
  google_maps_flutter: ^2.1.1
  flutter_polyline_points: ^2.0.0
  # flutter_map: ^3.1.0
  # flutter_map_location_marker: ^5.3.0
  # mapbox_search: ^3.2.0
  # flutter_mapbox_autocomplete: ^2.0.0
  # mapbox_gl: ^0.16.0
  # slider_button: ^2.0.0
  # system_alert_window: ^2.0.0
  # dash_bubble: ^2.0.0
  # flutter_geocoder: ^0.2.2-nullsafety
  # android_intent: ^3.0.0
  # flutter_shortcuts: ^1.3.0
  firebase_database: ^11.1.5
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/imagemCadastrar.png
    - assets/imagemCadastroMotorista.png
    - assets/Logo.png
    - assets/splash.png
    - assets/ic_motorista.png
    - assets/logo.svg
    - assets/logo_fundo.png
    - assets/images-not-found.jpeg
    - assets/notPerfil.png
    - assets/money.jpeg
    - assets/carteira.png
    - assets/setaCima.jpeg
    - assets/paste.png
    - assets/convidar.png
    - assets/carteira-icone.png
    - assets/carteira-icone-plus.png
    - assets/suporte.png
    - assets/money.png
    - assets/cartoes.png
    - assets/maquina-cartao.png
    - assets/pix.png
    - assets/dinheiro.svg
    - assets/transacoes.svg
    - assets/markerImage.png
    - assets/minhacasagps.svg
    - assets/motoristaIcon.png
    - assets/iconDestino.png
    - assets/money-holding.png
    - assets/suitcaseMotorista.png
    - assets/setaDrag.png
    - assets/mapa1.png
    - assets/mapaM.jpg
    - assets/notImage.jpg
    - assets/man.png
    - assets/proibidoOculos.jpg
    - assets/sun.jpg
    - assets/mais.svg
    - .env
    - assets/toques/toque_motorista_corrida_aceita.mp3 
    - assets/toques/toque_motorista_corrida_finalizada.mp3 
    - assets/toques/toque_botao_online_motorista.mp3
    - assets/toques/toque_clique_no_botao_de_enviar_mensagem_motorista_e_passageiro.mp3
    - assets/toques/toque_corrida_cancelada_pelo_passageiro_motorista.mp3
    - assets/toques/toque_corrida_cancelada_pelo_passageiro_motorista.caf
    - assets/toques/viagemdisponivel.mp3
    - assets/toques/viagemdisponivel.caf
    - assets/toques/CORRIDA_CANCELADA.mp3
    - assets/toques/CORRIDA_CANCELADA.caf
    - assets/Icones/apple_store.jpg
    - assets/Icones/google_play.jpg
    - assets/Vector.svg

  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android_12:
    color: "#ffffff"
    image: assets/splash.png
  android: true
  ios: true
  web: false
  fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_motorista.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/ic_motorista.png"